name: 📖 Documentation Issue
description: Share an issue to fix or enhancement to make in the documentation.
labels:
  - 'documentation'
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the issue to fix or enhancement to make in the documentation.
      placeholder: |
        Description
    validations:
      required: true