name: 🚨 Bug Report
description: Report a bug or issue.
labels:
  - 'bug'
body:
  - type: input
    id: github-local-actions-version
    attributes:
      label: Github Local Actions Version
      description: |
        What version of `Github Local Actions` are you using? This can be obtained from the standard `Extensions` view.
      placeholder: |
        v#.#.#
    validations:
      required: true
  - type: input
    id: act-version
    attributes:
      label: Act Version
      description: |
        What version of `act` are you using? This can be obtained from the `Components` view or by running `act --version`.
      placeholder: |
        act version #.#.#
    validations:
      required: true
  - type: input
    id: github-repository-link
    attributes:
      label: GitHub Repository Link
      description: |
        If your GitHub repository is public, provide a link to help us troubleshoot the problem.
      placeholder: |
        https://github.com/...
    validations:
      required: false
  - type: textarea
    id: workflow-content
    attributes:
      label: Workflow Content
      description: |
        Share your **entire** workflow here.
      placeholder: |
        name: My workflow
        on: ['push', 'schedule']
        jobs:
          test:
            runs-on: ubuntu-latest
          env:
            KEY: VAL
        [...]
      render: yml
    validations:
      required: false
  - type: textarea
      id: act-command-used
      attributes:
        label: Act Command Used
        description: |
          Share the entire act command which was used. This can be obtained from the VS Code task used to execute the workflow.
          If you no longer have the task open, you can select `View Output` from the `History` view and find it on the first line of the log file.
          ⚠️ Please make sure all sensitive information is removed. ⚠️
        placeholder: |
          act -P ubuntu-latest=node:12 -v ...
        render: sh
      validations:
        required: false
  - type: textarea
    id: act-command-output
    attributes:
      label: Act Command Output
      description: |
        Copy and paste any relevant log output from the VS Code task or log file. This will be automatically formatted into code, so no need for backticks.
        ⚠️ Please make sure all sensitive information is removed. ⚠️
      placeholder: |
        Use `act -v` for verbose output
      render: sh
    validations:
      required: false
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: |
        Describe the bug you encountered and share all steps to reproduce it.
    validations:
      required: true
  - type: textarea
    id: act-bug-report
    attributes:
      label: Act Bug Report
      description: |
        Provide the output of `act --bug-report`
      placeholder: |
        act --bug-report
      render: yml
    validations:
      required: false