name: 📖 Documentation Issue
description: Report an issue or enhancement regarding the documentation.
labels:
  - 'documentation'
body:
  - type: textarea
    id: description
    attributes:
      description:
        label: Description
        description: |
          Describe the issue or enhancement regarding the documentation.
    validations:
      required: true